export enum NavigatorConstants {
  BOTTOM_TAB_STACK = 'BOTTOM_TAB_STACK',
  APP_STACK = 'APP_STACK',
  HOME_SCREEN = 'HOME_SCREEN',
  TICKETS_SCREEN = 'TICKETS_SCREEN',
  MAP_SCREEN = 'MAP_SCREEN',
  INFO_SCREEN = 'INFO_SCREEN',
}
